# -*- coding: utf-8 -*-
"""Tarea de Simulación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cXlt8eu-pogTTkyWC6M_S7YPkeTwFmPo
"""

"""
===============================================================================
JUEGO DE YAHTZEE - SIMULACIÓN MONTECARLO PARA 2 JUGADORES
Gabriela Andrea Machado Silva
===============================================================================
"""

import random
from collections import Counter

# ==============================
# FUNCIONES ESTADÍSTICAS
# ==============================

def media(lista):
    return sum(lista) / len(lista)

def desviacion(lista):
    m = media(lista)
    return (sum((x - m) ** 2 for x in lista) / len(lista)) ** 0.5


# Clase Yahtzee


class Yahtzee:
    def __init__(self):
        self.categorias = {
            'Unos': None, 'Dos': None, 'Tres': None, 'Cuatros': None,
            'Cincos': None, 'Seises': None, 'Trío': None, 'Póker': None,
            'Full House': None, 'Escalera Corta': None, 'Escalera Larga': None,
            'Yahtzee': None, 'Chance': None
        }
        self.puntuacion_total = 0
        self.bono_superior = 0

    def lanzar_dados(self, num_dados=5):
        return [random.randint(1, 6) for _ in range(num_dados)]

    def calcular_puntuacion(self, dados, categoria):
        contador = Counter(dados)

        if categoria == 'Unos': return dados.count(1) * 1
        if categoria == 'Dos': return dados.count(2) * 2
        if categoria == 'Tres': return dados.count(3) * 3
        if categoria == 'Cuatros': return dados.count(4) * 4
        if categoria == 'Cincos': return dados.count(5) * 5
        if categoria == 'Seises': return dados.count(6) * 6

        if categoria == 'Trío':
            return sum(dados) if any(v >= 3 for v in contador.values()) else 0

        if categoria == 'Póker':
            return sum(dados) if any(v >= 4 for v in contador.values()) else 0

        if categoria == 'Full House':
            return 25 if sorted(contador.values()) == [2, 3] else 0

        if categoria == 'Escalera Corta':
            sets = [{1,2,3,4}, {2,3,4,5}, {3,4,5,6}]
            return 30 if any(s.issubset(dados) for s in sets) else 0

        if categoria == 'Escalera Larga':
            return 40 if set(dados) in [{1,2,3,4,5}, {2,3,4,5,6}] else 0

        if categoria == 'Yahtzee':
            return 50 if len(contador) == 1 else 0

        if categoria == 'Chance':
            return sum(dados)

        return 0

    def verificar_bono_superior(self):
        suma = sum(
            self.categorias[cat] for cat in ['Unos','Dos','Tres','Cuatros','Cincos','Seises']
            if self.categorias[cat] is not None
        )
        if suma >= 63:
            self.bono_superior = 35
            return 35
        return 0

    def categorias_disponibles(self):
        return [c for c, v in self.categorias.items() if v is None]


# CLASE JUGADOR

class Jugador:
    def __init__(self, nombre):
        self.nombre = nombre
        self.tarjeta = Yahtzee()

    def decidir_dados_montecarlo(self, dados, sims=50):
        mejor = dados
        mejor_score = -1

        for _ in range(sims):
            k = random.randint(0, 5)
            mantener = random.sample(dados, k) if k > 0 else []
            nuevos = [random.randint(1,6) for _ in range(5-len(mantener))]
            combinacion = mantener + nuevos

            score = sum(combinacion)

            if score > mejor_score:
                mejor_score = score
                mejor = mantener

        return mejor

    def elegir_categoria(self, dados):
        disponibles = self.tarjeta.categorias_disponibles()
        mejor = None
        mejor_puntaje = -1

        for cat in disponibles:
            punt = self.tarjeta.calcular_puntuacion(dados, cat)
            if punt > mejor_puntaje:
                mejor_puntaje = punt
                mejor = cat

        return mejor


# Clase juego

class Juego:
    def __init__(self, n1, n2):
        self.j1 = Jugador(n1)
        self.j2 = Jugador(n2)

    def turno(self, jugador, mostrar=True):
        if mostrar:
            print(f"\n Turno de {jugador.nombre}")

        dados = jugador.tarjeta.lanzar_dados()
        if mostrar:
            print("Lanzamiento 1:", dados)

        for i in range(2):
            mantener = jugador.decidir_dados_montecarlo(dados)
            nuevos = jugador.tarjeta.lanzar_dados(5 - len(mantener))
            dados = mantener + nuevos

            if mostrar:
                print(f" Lanzamiento {i+2}:", dados)

        categoria = jugador.elegir_categoria(dados)
        puntos = jugador.tarjeta.calcular_puntuacion(dados, categoria)

        jugador.tarjeta.categorias[categoria] = puntos
        jugador.tarjeta.puntuacion_total += puntos

        if mostrar:
            print(f"{categoria} = {puntos} | Total: {jugador.tarjeta.puntuacion_total}")

    def jugar(self, mostrar=True):
        for _ in range(13):
            self.turno(self.j1, mostrar)
            self.turno(self.j2, mostrar)

        if mostrar:
            print("\n RESULTADOS")
            print(self.j1.nombre, ":", self.j1.tarjeta.puntuacion_total)
            print(self.j2.nombre, ":", self.j2.tarjeta.puntuacion_total)

    def ganador(self):
        if self.j1.tarjeta.puntuacion_total > self.j2.tarjeta.puntuacion_total:
            return self.j1.nombre
        elif self.j2.tarjeta.puntuacion_total > self.j1.tarjeta.puntuacion_total:
            return self.j2.nombre
        return "Empate"



# ANÁLISIS MONTECARLO

def analisis(sim=50):
    j1 = []
    j2 = []

    for _ in range(sim):
        juego = Juego("A", "B")
        juego.jugar(False)
        j1.append(juego.j1.tarjeta.puntuacion_total)
        j2.append(juego.j2.tarjeta.puntuacion_total)

    print("\n ANÁLISIS")
    print("J1 promedio:", media(j1))
    print("J1 desviación:", desviacion(j1))
    print("J2 promedio:", media(j2))
    print("J2 desviación:", desviacion(j2))


# MAIN

if __name__ == "__main__":

    print(" YAHTZEE MONTECARLO")

    # Semilla opcional
    usar_seed = input("¿Usar semilla fija? (s/n): ").lower()
    if usar_seed == "s":
        random.seed(42)

    # Nombres
    while True:
        n1 = input("Jugador 1: ").strip() or "Jugador 1"
        n2 = input("Jugador 2: ").strip() or "Jugador 2"

        if n1 != n2:
            break
        print(" Nombres iguales, intenta de nuevo")

    print(f"\n {n1} vs {n2}")

    juego = Juego(n1, n2)
    juego.jugar()

    print("\n Ganador:", juego.ganador())

    # Simulaciones
    sims = input("\nNúmero de simulaciones (por defecto 50): ")
    sims = int(sims) if sims.isdigit() else 50

    analisis(sims)
